### Ex1

#### a) si b)

In [30]:
import numpy as np

matrix = np.array([[1,2,3,4],
                  [5,2,7,8],
                  [9,2,11,12],
                  [13,2,15,16],
                  [17,2,19,20]])
def min_max(matrix):
    maxim = np.max(matrix,axis=0)
    minim = np.min(matrix,axis=0)
    matrix = np.where(minim==maxim,matrix,(matrix-minim)/(maxim - minim))
    return matrix
min_max(matrix)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


array([[0.  , 2.  , 0.  , 0.  ],
       [0.25, 2.  , 0.25, 0.25],
       [0.5 , 2.  , 0.5 , 0.5 ],
       [0.75, 2.  , 0.75, 0.75],
       [1.  , 2.  , 1.  , 1.  ]])

### Ex2

In [36]:
print(len(matrix))
def ones(matrix):
    matrixS = np.ones((len(matrix),1))
    print(matrixS)
    return np.hstack((matrixS,matrix))
ones(matrix)

5
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


array([[ 1.,  1.,  2.,  3.,  4.],
       [ 1.,  5.,  2.,  7.,  8.],
       [ 1.,  9.,  2., 11., 12.],
       [ 1., 13.,  2., 15., 16.],
       [ 1., 17.,  2., 19., 20.]])

### Ex4

In [38]:
print(np.linalg.pinv(matrix))

[[-0.15769231 -0.09807692 -0.03846154  0.02115385  0.08076923]
 [ 0.16923077  0.10769231  0.04615385 -0.01538462 -0.07692308]
 [ 0.01153846  0.00961538  0.00769231  0.00576923  0.00384615]
 [ 0.09615385  0.06346154  0.03076923 -0.00192308 -0.03461538]]
