### CRC

In [12]:
print("M(x)")
m='110111001000010'
print (m)
print("Codul:")
print('C(x)')
c='1011'
print (c)
print('T(x):')
t=t=m+'0'*(len(c)-1)
print(t)
def logical_xor(a, b):
    if a == b:
        return 0
    else:
        return 1

def mesaj(mesaj,cod):
    while len(mesaj)>=4:
        a=mesaj[0:len(cod)] #subsir de lungimea codului
        b=''
        for i in range(0,len(cod)):
            b+=str(logical_xor(a[i],cod[i]))
        mesaj=mesaj.replace(mesaj[0:len(cod)],b)
        while mesaj[0]=='0' and len(mesaj)>=len(cod): 

            #STERGE TOTI 0
            mesaj=mesaj[1:]
    return mesaj

r=mesaj(t,c)
print ('Restul:',r)
print()

def mesajTrimis(mesaj,rest):
    a=mesaj[len(mesaj)-len(rest):]
    b=''
    for i in range(0,len(rest)):
        b+=str(logical_xor(a[i],rest[i]))
    mesaj=mesaj[0:len(mesaj)-len(rest)]
    mesaj=mesaj+b
    return mesaj

def verificareEroare(err):
        for i in err:
            if i=='1':
                return False
        return True

final_message=mesajTrimis(t,r)
eroare=mesaj(final_message,c)
if verificareEroare(eroare)==True:
    print("Mesajul final:",final_message,'este corect')
else:
     print("Mesajul final:",final_message,'este incorect')


M(x)
110111001000010
Codul:
C(x)
1011
T(x):
110111001000010000
Restul: 110

Mesajul final: 110111001000010110 este corect


### BitDeParitate


In [23]:
import numpy as np
print("M(x)")
m='110111001000010'
print (m)
def adding_zero(inc):
    while len(inc) <= 7:
        inc += '0'
    return inc
        
def create_matrix(m):
    n = 7
    #spliting m
    table = np.array([m[i:i+n] for i in range(0, len(m), n)])
    #adding needed zeros to last row
    if len(table[-1]) < 7:
        table[-1] = adding_zero(table[-1])
    print(table)
    #convert into matrix
    matrix = np.zeros((len(table),7))
    for i in range(len(table)):
        for j in range(len(table[i])):
            matrix[i][j] = table[i][j]
    return matrix

def bits(matrix):
    
            

M(x)
110111001000010
['1101110' '0100001' '0000000']
[[1. 1. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]
